name: wayback-if-down.github.io

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: wayback-if-down.github.io
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.9"
          cache: pip
      - name: Install python dependencies
        run: pip install --no-dependencies -r requirements.txt
      - name: Run tests
        run: pytest -v --cov=main --cov-fail-under=100 --cov-report=term-missing
